import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import TRPCProvider from '@/components/provider/trpc-provider';
import AuthProvider from '@/components/provider/auth-provider';

import './globals.css';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin']
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin']
// });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

type RootLayoutProps = { children: React.ReactNode };

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <ClerkProvider afterSignOutUrl='/'>
      <html lang='en'>
        <body className={inter.className}>
          <TRPCProvider>
            {/* <AuthProvider> */}
            {children}
            {/* </AuthProvider> */}
          </TRPCProvider>
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
